openapi: 3.0.1
info:
  title: defaultTitle
  description: defaultDescription
  version: '0.1'
servers:
  - url: 'http://localhost:5000'
paths:
  /suggestions:
    post:
      description: Adds a suggestion to database.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                id:
                  type: string
                choice:
                  type: string
            examples:
              '0':
                value: "{\r\n  \"name\": \"jakob\",\r\n  \"choice\": \"predlog1\",\r\n  \"id\": \"6NJXVY0B8T\"\r\n}"
              '1':
                value: "{\r\n  \"name\": \"janez\",\r\n  \"choice\": \"predlog2\",\r\n  \"id\": \"6NJXVY0B8T\"\r\n}"
              '2':
                value: "{\r\n  \"name\": \"janez\",\r\n  \"choice\": \"predlog2\",\r\n  \"id\": \"6NJXVY0B8T\"\r\n}"
      responses:
        '200':
          description: Auto generated using Swagger Inspector
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
              examples:
                '0':
                  value: |
                    {
                      "status": "Thanks! Suggestion added."
                    }
                '1':
                  value: |
                    {
                      "status": "Thanks! Suggestion added."
                    }
                '2':
                  value: |
                    {
                      "status": "You already suggested this one!"
                    }
      servers:
        - url: 'http://localhost:5000'
    servers:
      - url: 'http://localhost:5000'
  /wswe:
    get:
      description: Returns ID used in unique link that user needs to share with colleagues.
      responses:
        '200':
          description: Auto generated using Swagger Inspector
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '0':
                  value: >
                    {
                    "id": "IYAQ899B8A"
                    }
      servers:
        - url: 'http://localhost:5000'
    post:
      description: Returns a final decision for specified unique ID.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
            examples:
              '0':
                value: "{\r\n  \"id\": \"6NJXVY0B8T\"\r\n}"
      responses:
        '200':
          description: Auto generated using Swagger Inspector
          content:
            application/json:
              schema:
                type: object
                properties:
                  decision:
                    type: string
                  name:
                    type: string
              examples:
                '0':
                  value: |
                    {
                      "decision": "predlog1", 
                      "name": "jakob"
                    }
      servers:
        - url: 'http://localhost:5000'
    servers:
      - url: 'http://localhost:5000'